<a href="https://colab.research.google.com/github/dilipkm007/Mathematics/blob/main/Basic_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

<h1>Creating Tensor</h1>

In [13]:
m1 = np.array([[5, 12, 6], [-3, 0, 14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [14]:
m2 = np.array([[9, 8, 7], [1, 3, -5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [15]:
t = np.array([m1, m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

<h1>Checking the shape of Tensor<h1>

In [16]:
t.shape

(2, 2, 3)

*Here in shape we see that 2 matrix each 2X3*


<h1>Another way to create Tensor</h1>

In [17]:
t_manually = np.array([[[5, 12, 6], [-3, 0, 14]], [[9, 8, 7], [1, 3, -5]]])
t_manually 

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [18]:
t_manually .shape

(2, 2, 3)