<a href="https://colab.research.google.com/github/dilipkm007/Mathematics/blob/main/DotProduct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np

#**Dot Product of vectors and scalars**

In [21]:
x = np.array([2, 8, -4])
y = np.array([1, -7, 3])

In [22]:
np.dot(x, y)

-66

In [23]:
u = np.array([0, 1, 2, 3])
v = np.array([3, 2, 1, 0])
np.dot(u, v)

4

#**Scalrs dot product**

In [24]:
np.dot(6, 7)

42

In [25]:
np.dot(-2,-3)

6

#**Scalar and vector dot product**

In [26]:
z = np.array([6, 2, 4, 3])
5*z

array([30, 10, 20, 15])

# **Scalars * Matrix**

In [27]:
A = np.array([[5, 12, 6], [-3, 0, 14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [28]:
3 * A

array([[15, 36, 18],
       [-9,  0, 42]])

# **Matrix Multiplications**

In [29]:
B = np.array([[2, -1], [8, 0], [3, 0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [30]:
np.dot(A, B)

array([[124,  -5],
       [ 36,   3]])