<a href="https://colab.research.google.com/github/dilipkm007/Mathematics/blob/main/OperationOfMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np

## **Addition**



In [32]:
m1 = np.array([[5, 12, 6], [-3, 0, 14]])
m2 = np.array([[9, 8, 7], [1, 3, -5]])


In [33]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

## **Substraction**

In [34]:
m3 = np.array([[5, 3], [-2, 4]])
m4 = np.array([[7, -5], [3, 8]])

In [35]:
m3 - m4

array([[-2,  8],
       [-5, -4]])

# **Calculation of Vectors**

In [36]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([5, 4, 3, 2, 1])

In [37]:
v1 + v2

array([6, 6, 6, 6, 6])

In [38]:
v1 - v2

array([-4, -2,  0,  2,  4])

##**Exceptions(addition with a scalar)**
The result from it has a meaning in term of arrays, but not in term of linear algebra.

In [39]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [41]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [43]:
v1

array([1, 2, 3, 4, 5])

In [42]:
v1 + 1

array([2, 3, 4, 5, 6])

In [44]:
m1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [45]:
v1 + np.array([1])

array([2, 3, 4, 5, 6])