<a href="https://colab.research.google.com/github/dilipkm007/Mathematics/blob/main/TransposingMatrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

#**Tansposing Matrix using numpy**

In [13]:
A = np.array([[5, 12, 6], [-3, 0, 14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [14]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [15]:
C = np.array([[4, -5], [8, 12], [-2, -3], [19, 0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [16]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

#**Scalars Tranpose** 

In [17]:
s = np.array(5)
s

array(5)

In [19]:
s.T

array(5)

# **Vectors Transpose**

In [20]:
v = np.array([1, 2, 3])
v

array([1, 2, 3])

In [21]:
v.T

array([1, 2, 3])

In [22]:
v_reshaped = v.reshape(1, 3)
v_reshaped

array([[1, 2, 3]])

In [23]:
v_reshaped.T

array([[1],
       [2],
       [3]])